BoostryJP/ibet-Wallet-API

app/model/db/idx_position.py, batch/indexer_Position_Bond.py, batch/indexer_Position_Coupon.py, batch/indexer_Position_Membership.py, batch/indexer_Position_Share.py, tests/batch/indexer_Position_Bond_test.py, tests/batch/indexer_Position_Coupon_test.py, tests/batch/indexer_Position_Membership_test.py, tests/batch/indexer_Position_Share_test.py
**Draft**
close #1128 
1. 
> Create a table to save the processed block number, and batch start processing from that number.
> refer https://github.com/BoostryJP/ibet-Prime/blob/dev-22.3/batch/indexer_position_bond.py#L70
2. 
> Data of duplicate combinations within the specified range will be deleted and then synchronized.
~~I added mixins and made position processors inherit them.~~
~~Is it OK?~~
* I'm going to implement methods to each processors, not use mixins.
=> feat: improve indexer batch

app/api/common/base.py, app/api/v2/token.py, app/main.py, app/model/db/__init__.py, app/model/db/tokenholders.py, batch/indexer_Token_Holders.py, bin/healthcheck_indexer.sh, bin/run_indexer.sh, docs/ibet_wallet_api_v2.yaml, docs/ibet_wallet_api_v3.yaml, migrations/versions/028_create_token_holders_list.py, migrations/versions/029_create_token_holder.py, tests/app/v2_token_tokenholderscollection_test.py, tests/app/v2_token_tokenholderscollectionid_test.py, tests/batch/indexer_Token_Holders_test.py, tests/conftest.py, tests/contract_modules.py
Close #1134 
https://github.com/BoostryJP/ibet-Wallet-API/blob/b0ba9c92653a0b1f8525f3d58c7fbc0e90c710e7/docs/ibet_wallet_api_v2.yaml#L1996
* Added POST endpoint.
* This api expect “contract_address” in path, “list_id” and “block_number” in body.
* ”list_id” is assumed to be UUID.
* If existing combinations of block_number and contract_address is given, this api will return existing list_id.
https://github.com/BoostryJP/ibet-Wallet-API/blob/b0ba9c92653a0b1f8525f3d58c7fbc0e90c710e7/docs/ibet_wallet_api_v2.yaml#L2064 
* This api expect “contract_address” and “list_id “ in path.
* It syncs all events from 0 to given block number.
* If it has already collected events from 0 to some block number and stored data in DB, it can reuse the data.
* Token holders address is excluding issuer address as …
=> feat: add function for obtaining a list of holders in a given block number

tests/batch/indexer_Consume_Coupon_test.py, tests/batch/indexer_DEX_test.py, tests/batch/indexer_Token_Holders_test.py, tests/batch/indexer_TransferApproval_test.py, tests/batch/indexer_Transfer_test.py
close #1144 
**Fixed only Unit test.**
=> fix: add rollback before second query in unit test

app/api/v2/admin.py, app/api/v2/token.py, app/config.py, app/errors.py, app/model/blockchain/__init__.py, app/model/blockchain/token.py, app/model/db/__init__.py, app/model/db/idx_token.py, app/model/db/idx_token_list.py, batch/indexer_Token_Detail.py, batch/indexer_Token_Detail_ShortTerm.py, batch/indexer_Token_List.py, bin/healthcheck_indexer.sh, bin/run_indexer.sh, docs/ibet_wallet_api_v2.yaml, migrations/versions/035_create_bond_token.py, migrations/versions/036_create_share_token.py, migrations/versions/037_create_membership_token.py, migrations/versions/038_create_coupon_token.py, migrations/versions/039_create_token_list.py, migrations/versions/040_create_idx_token_list_block_number.py, tests/app/v2_admin_Tokens_POST_test.py, tests/app/v2_token_coupontokens_test.py, tests/app/v2_token_membershiptokens_test.py, tests/app/v2_token_sharetokens_test.py, tests/app/v2_token_straightbondtokens_test.py, tests/batch/indexer_Token_Detail_ShortTerm_test.py, tests/batch/indexer_Token_Detail_test.py, tests/batch/indexer_Token_List_test.py
#1163 
1. Added 2 batches
which get token detail data from quorum at fixed interval.
2. Added cache functionality to following API endpoint
```
GET /Token/StraightBond
GET /Token/Share
GET /Token/Membership
GET /Token/Coupon
```
- **Environment variables added**
- **Migration files added**
=> feat: Add indexer batch for token details

app/api/v2/admin.py, app/api/v2/company.py, app/api/v2/eth.py, app/api/v2/market_information.py, app/api/v2/nodeInfo.py, app/api/v2/notification.py, app/api/v2/order_list.py, app/api/v2/position.py, app/api/v2/statistics.py, app/api/v2/token.py, app/api/v2/token_abi.py, app/api/v2/user.py, app/api/v3/e2e_message.py, app/api/v3/events.py, app/api/v3/notification.py, app/api/v3/position.py, app/config.py, app/main.py, app/middleware/__init__.py, app/middleware/response_logger.py
Changed the implementation method of API access logs.
Currently, the routing function performs `LOG.info` to output the access log, but this has been refactored to be performed by the falcon middleware.
The log output by the new method differs from the current method in that it is a response log.
In case of normal response
```
[2022-07-07 19:02:05 +0900] [82957] [INFO] [ACCESS-LOG] GET /v2/ABI/Coupon 200 OK
```
In case of error response
```
[2022-07-07 19:02:10 +0900] [82957] [INFO] [ACCESS-LOG] GET /v2/ABI/Coupooon 404 Not Found
```
=> feat: Change API access logging method

app/middleware/response_logger.py
I have made improvements to the response log.
I added API response times to the response log to make it easier to analyze API response performance.
> レスポンスログの改善を行いました。APIの応答性能の分析が簡単に行えるようにするために、レスポンスログにAPI応答時間を追加しました。
```
[2022-07-23 23:57:32 +0900] [16452] [INFO] [ACCESS-LOG] GET /v1/Accounts 200 OK (0.141566sec)
```
=> feat: add response time to response log

app/api/v3/notification.py, app/config.py, app/model/db/notification.py, batch/processor_Notifications_Token.py, bin/healthcheck_processor_notification.sh, bin/run_processor_notification.sh, docs/ibet_wallet_api_v2.yaml, docs/ibet_wallet_api_v3.yaml, healthcheck.sh, run.sh, tests/batch/processor_Notifications_Token_test.py, tests/conftest.py, tests/contract_modules.py
Close: #1183 
- ```batch/processor_Notifications_Token.py```
- Add watcher for ApplyTransfer/CancelTransfer/ApproveTransfer event.
> ApplyTransfer/CancelTransfer/ApproveTransferイベントの監視モジュールを追加しました。
- ```EXCHANGE_NOTIFICATION_ENABLED```
- Add new variable so that we choose notification processor to run.
- If you do not provide a value for that, exchange notification processor will not start. This will affect those who are already using exchange notification batches.
- ```RUN_MODE```
- Add "batch" mode so that indexer and processor run in one container.
> ```EXCHANGE_NOTIFICATION_ENABLED```
> 起動する通知バッチを選択できるようにしました。値が設定されていなければ、取引系通知バッチは起動しません。
> 既に取引系通知バッチを使用している場合は影響があります。
> ```RUN_MODE```
> batchモードを追加しました。
=> feat: token notification type(`ApplyTransfer`/`CancelTransfer`/`ApproveTransfer`)

app/api/v3/token.py, tests/app/v3_token_coupontokens_test.py, tests/app/v3_token_membershiptokens_test.py, tests/app/v3_token_sharetokens_test.py, tests/app/v3_token_straightbondtokens_test.py
Close #1185 
- GET: /v3/Token/StraightBond
- GET: /v3/Token/Share
- GET: /v3/Token/Membership
- GET: /v3/Token/Coupon
```
curl --location --request GET 'http://localhost:5000/v3/Token/StraightBond?
address_list=0x012345678901234567890123456789012' \
--header 'Accept: */*'
```
```
{
"meta": {
"code": 88,
"message": "Invalid Parameter",
"description": "invalid token_address: 0x012345678901234567890123456789012"
}
}
```
=> fix: token_address validation error is not handled in ```v3/token``` API endpoint

app/api/routers/eth.py, app/config.py, tests/app/eth_SendRawTransaction_test.py
Close: #1202 
- Change default value of `TRANSACTION_WAIT_TIMEOUT` from 120sec to 5sec.
- Define `TRANSACTION_WAIT_POLL_LATENCY` (which is an argument to be passed to `wait_for_transaction()`) set default value of it 0.5 sec.
> `TRANSACTION_WAIT_TIMEOUT` のデフォルト値を120秒から5秒に変更しました。
> `TRANSACTION_WAIT_POLL_LATENCY`を新たに追加し、デフォルト値を0.5秒としました。
- Apply `TRANSACTION_WAIT_POLL_LATENCY` values to `wait_for_transaction_receipt()` in Get: `/Eth/SendRawTransaction`
> `TRANSACTION_WAIT_POLL_LATENCY`を`/Eth/SendRawTransaction`内の`wait_for_transaction_receipt()`で使用するようにしました。
=> fix: timeout/poll_latency value of wait for transaction receipt in SendRawTransaction API

migrations/versions/046_alter_bond_token.py, migrations/versions/047_alter_share_token.py
- Expanded bond and share memo field length from 2000 to 10000.
=> feat: expand token memo field length

app/api/routers/token.py, app/model/db/__init__.py, app/model/db/idx_lock_unlock.py, app/model/db/idx_transfer.py, app/model/schema/__init__.py, app/model/schema/bc_explorer.py, app/model/schema/token.py, batch/indexer_Transfer.py, docs/ibet_wallet_api.yaml, migrations/versions/051_alter_transfer.py, tests/app/position_PositionCouponContractAddress_test.py, tests/app/position_PositionCoupon_test.py, tests/app/token_TransferHistory_test.py, tests/batch/indexer_Transfer_test.py, tests/contract_modules.py
Close #1303 
- Added new columns about source event data to `IDXTransfer`
- Added some logic to batch `indexer_Transfer` so that source event data is stored.
- Added some query param to `/Token/{token_address}/TransferHistory`
=> feat: store source event data as idx_transfer

requirements.lock, requirements.txt, tests/requirements.txt
Upgrade packages.
- FastAPI etc.
- https://github.com/tiangolo/fastapi/releases/tag/0.89.0
- https://github.com/tiangolo/fastapi/releases/tag/0.89.1
- https://github.com/tiangolo/fastapi/releases/tag/0.90.0
- https://github.com/tiangolo/fastapi/releases/tag/0.90.1
- https://github.com/tiangolo/fastapi/releases/tag/0.91.0
=> Bump FastAPI to 0.91.0

cmd/explorer/src/connector/__init__.py, cmd/explorer/src/gui/explorer.css, cmd/explorer/src/gui/screen/block.py, cmd/explorer/src/gui/screen/transaction.py
Fix: #1320
- Change client timeout from 10 sec to 30 sec.
- Added client cache.
- Reduce the number of blocks initially fetched from 300 to 100.
=> fix: timeout/cache/limit parameters in BC Explorer

app/api/routers/position.py, app/api/routers/token.py, app/api/routers/token_bond.py, app/api/routers/token_coupon.py, app/api/routers/token_membership.py, app/api/routers/token_share.py
- From past release, if the connection to quorum is broken during an API endpoint request, a `Block Synchronisation down` message is displayed as an error. 
- Considering the frequency with this, it would be preferable to make it  as warning.
- So changed message level about web3 exception in GET endpoints.
=> hotfix: change message level about web3 in GET endpoint

app/database/__init__.py, cmd/explorer/README.md, cmd/explorer/src/gui/explorer.py, cmd/explorer/src/gui/rendarable/block_detail_info.py, cmd/explorer/src/gui/rendarable/tx_detail_info.py, cmd/explorer/src/gui/screen/base.py, cmd/explorer/src/gui/screen/block.py, cmd/explorer/src/gui/screen/traceback.py, cmd/explorer/src/gui/screen/transaction.py, cmd/explorer/src/gui/widget/base.py, cmd/explorer/src/gui/widget/block_detail_view.py, cmd/explorer/src/gui/widget/block_list_table.py, cmd/explorer/src/gui/widget/block_list_view.py, cmd/explorer/src/gui/widget/menu.py, cmd/explorer/src/gui/widget/query_panel.py, cmd/explorer/src/gui/widget/traceback.py, cmd/explorer/src/gui/widget/tx_detail_view.py, cmd/explorer/src/gui/widget/tx_list_view.py, cmd/explorer/src/main.py
- Some IDE environments were causing module import errors, so I reviewed the import way.
- Fixed some minor bugs.
=> Minor improvements and bug fixes in bc-explorer tui

ENV_LIST.md, app/api/routers/position.py, app/config.py, app/model/db/idx_agreement.py, app/model/db/idx_consume_coupon.py, app/model/db/idx_lock_unlock.py, app/model/db/idx_order.py, app/model/db/idx_transfer.py, app/model/db/idx_transfer_approval.py, app/model/db/listing.py, app/model/db/notification.py, app/model/schema/admin.py, app/model/schema/position.py, app/model/schema/token.py, batch/indexer_Consume_Coupon.py, batch/indexer_DEX.py, batch/processor_Notifications_Coupon_Exchange.py, batch/processor_Notifications_Membership_Exchange.py, batch/processor_Notifications_Token.py, docs/ibet_wallet_api.yaml, poetry.lock, pyproject.toml, tests/app/notification_NotificationsId_POST_test.py, tests/app/notification_NotificationsRead_test.py, tests/app/token_TransferApprovalHistory_test.py
Close: #961 
- Replaced all `JST` definition to `local timezone`.
- Local timezone can be set via config.
- [ZoneInfo](https://www.python.jp/pages/python3.9.html#zoneinfo%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB) is used.
=> feat: Localize datetime and return it in API response

Dockerfile
Close: #1349 
---
- Changed poetry installation way from [official installer](https://python-poetry.org/docs/#installing-with-the-official-installer) to [manual](https://python-poetry.org/docs/#installing-manually) so as not to create poetry python environment
=> feat: cleanup unused setuptools

tests/app/config_test.py, tests/app/dex_market_CouponOrderBook_test.py, tests/app/dex_market_MembershipOrderBook_test.py, tests/app/eth_SendRawTransactionNowait_test.py, tests/batch/processor_Notifications_Token_test.py, tests/conftest.py, tests/contract_modules.py
close #1368 
- Fixed unit test code to remove `PytestRemovedIn8Warning`.
- Relatedly, I've also removed other warnings that occur when running unit tests.
=> Remove PytestRemovedIn8Warning

app/api/routers/position.py, app/model/db/idx_position.py, app/model/schema/__init__.py, app/model/schema/position.py, docs/ibet_wallet_api.yaml, tests/app/position_PositionCoupon_test.py, tests/app/position_PositionMembership_test.py, tests/app/position_PositionShare_test.py, tests/app/position_PositionStraightBond_test.py, tests/app/position_Position_test.py, tests/batch/indexer_Position_Bond_test.py, tests/batch/indexer_Position_Coupon_test.py, tests/batch/indexer_Position_Membership_test.py, tests/batch/indexer_Position_Share_test.py
Close: #1354 
- GET: **/Position/{account_address}**
- return position info across all token types.
- result can be filtered with `token_type_list` query.
=> feat: add Position API that does not include the token type in the API path

poetry.lock
- packages
- alembic 1.10.3->[1.11.1](https://github.com/sqlalchemy/alembic/releases/tag/rel_1_11_1)
- fastapi 0.95.0->[0.95.2](https://github.com/tiangolo/fastapi/releases/tag/0.95.2)
- email-validator 1.3.1->[2.0.0-post2](https://github.com/JoshData/python-email-validator/blob/main/CHANGELOG.md#200-april-15-2023)
- validation logic is not changed
- orjson 3.8.9->[3.8.12](https://github.com/ijl/orjson/releases)
- psycopg 3.1.8->[3.1.9](https://www.psycopg.org/psycopg3/docs/news.html#psycopg-3-1-9)
- requests 2.28.2->[2.30.0](https://github.com/psf/requests/blob/main/HISTORY.md#2300-2023-05-03)
- sqlalchemy 2.0.9->[2.0.13](https://github.com/sqlalchemy/sqlalchemy/releases)
- and other develop dependencies.
=> Bump dependencies versions

poetry.lock
Updated various packages.
Among them, the currently used version of `requets` has the following vulnerabilities and has been patched.
https://github.com/advisories/GHSA-j8r2-6x86-q33q
=> Bump packages

app/api/routers/company_info.py, app/api/routers/token.py
Improve the performance of the `/Companies` API.
Since there was a logic that processed duplicated data in the loop processing, I eliminated the duplication of the data to be processed and improved the performance.
=> api: Eliminate duplication in owner list

poetry.lock
Upgrade cryptography to v41.0.3
https://cryptography.io/en/latest/changelog/#v41-0-3
=> Bump cryptography

bin/run_server.sh
- Removed unnecessary kill command from stop function in  `./bin/run_server.sh`.
- Currently, the `stop` function is not used from anywhere when server process is run in container environment.
=> Remove unnecessary line in server stop func

Dockerfile, tests/Dockerfile
Fixed warning like following in image build.
```bash
Step 10/19 : RUN . ~/.bash_profile  && pyenv install 3.11.2  && pyenv global 3.11.2  && pip install --upgrade pip
---> Running in 0662e9ecd5b9
Downloading Python-3.11.2.tar.xz...
-> https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tar.xz
Installing Python-3.11.2...
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/apl/.pyenv/versions/3.11.2/lib/python3.11/lzma.py", line 27, in <module>
from _lzma import *
ModuleNotFoundError: No module named '_lzma'
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?
Installed Python-3.11.2 to /home/apl/.pyenv/versions/3.11.2
```
=> Fix `liblzma` warning in image build

README.md, README_JA.md, poetry.lock, pyproject.toml
- Updated dependency packages
- web3.py is not included in updated packages because argument filters behavior in `get_logs()` function is changed from `6.10.0`.
=> Bump dependencies

app/api/routers/token.py, app/api/routers/user_info.py, app/model/db/__init__.py, app/model/db/user_info.py, app/model/schema/__init__.py, app/model/schema/token.py, app/model/schema/user_info.py, docs/ibet_wallet_api.yaml, migrations/versions/4164b4e8dfe6_v23_12_0_feature_1447.py, tests/app/token_TokenHolders_test.py, tests/app/token_TransferApprovalHistory_test.py, tests/app/token_TransferHistory_test.py, tests/app/userinfo_TaggingAccountAddress_test.py
Close: #1447
- Add an API to add tags to account addresses.
- `GET: /User/Tag`
- Add account tag as a request query for the following API.
- `GET: /Token//{token_address}/Holders`
- `GET: /Token/{token_address}/Holders/Count`
- `GET: /Token/{token_address}/TransferHistory`
- `GET: /Token/{token_address}/TransferApprovalHistory`
Currently, I have not made any changes to the `**/Search` API, but I think there is no problem in deleting it if it is not used.
=> Tagging account address

.pre-commit-config.yaml, app/api/routers/events.py, poetry.lock, pyproject.toml, tests/app/events_E2EMessagingEvents_test.py, tests/app/events_IbetEscrowEvents_test.py, tests/app/events_IbetSecurityTokenEscrowEvents_test.py, tests/app/events_IbetSecurityTokenInterfaceEvents_test.py
- I have updated the packages, focusing on packages for which vulnerabilities have been reported.
- https://github.com/BoostryJP/ibet-Wallet-API/security/dependabot/17
- https://github.com/BoostryJP/ibet-Wallet-API/security/dependabot/16
- https://github.com/BoostryJP/ibet-Wallet-API/security/dependabot/15
- Regarding web3py, the behavior of `get_logs` has changed, so the event search API implementation has been changed.
=> Bump vulnerable packages

app/database/__init__.py, app/log.py, batch/indexer_Block_Tx_Data.py, batch/indexer_CompanyList.py, batch/indexer_Consume_Coupon.py, batch/indexer_DEX.py, batch/indexer_Position_Bond.py, batch/indexer_Position_Coupon.py, batch/indexer_Position_Membership.py, batch/indexer_Position_Share.py, batch/indexer_Token_Detail.py, batch/indexer_Token_Detail_ShortTerm.py, batch/indexer_Token_Holders.py, batch/indexer_Token_List.py, batch/indexer_Transfer.py, batch/indexer_TransferApproval.py, batch/processor_Notifications_Coupon_Exchange.py, batch/processor_Notifications_Membership_Exchange.py, batch/processor_Notifications_Token.py, batch/processor_Send_Chat_Webhook.py, tests/batch/indexer_Block_Tx_Data_test.py, tests/batch/processor_Notifications_Token_test.py, tests/batch/processor_Send_Chat_Webhook_test.py
Fix: #1469 
- Modified so that async batches use same DB engine setting parameter which includes `expire_on_commit=False`.
- `expire_on_commit=False` parameter makes it enable to access model object once after batches run `commit()`.
In #1469, some batches used default DB engine setting and raised exceptions because it could not access model object after it run `commit()`. This PR is intended to fix it.
=> Fix to use same DB engine setting parameters in async batches

batch/indexer_Token_List.py, migrations/versions/3d3b90fda898_v24_3_0_feature_1483.py, tests/batch/indexer_Token_List_test.py
Close: #1483 
- Made TokenList indexer collect all TokenList items of ibet token regardless of token enable settings.
- Added migration file to initialize existing `idx_token_list_block_number`.
- Added some unit tests.
=> Collect all TokenList items regardless of token enable settings

app/api/routers/eth.py, app/model/schema/eth.py, docs/ibet_wallet_api.yaml, tests/app/eth_SendRawTransactionNowait_test.py, tests/app/eth_SendRawTransaction_test.py
Close: #1482 
- Detailed the response status of eth_sendRawTransaction to distinguish whether the error returned from quorum RPC is `already known`, `nonce too low` or a failure
- POST: `/Eth/SendRawTransaction`
- POST: `/Eth/SendRawTransactionNoWait`
=> Detailed the response status of eth_sendRawTransaction

batch/indexer_Token_Detail.py, batch/indexer_Token_Detail_ShortTerm.py
Fix: #1486 
- Fixed to use nested transaction on saving token cache in order to reuse Session object after failing to save a token cache.
=> Fixed to use nested transaction when saving token cache

app/api/routers/eth.py, tests/app/eth_SendRawTransactionNowait_test.py, tests/app/eth_SendRawTransaction_test.py
Close: #1519
- Verified that the error handling of `Web3RPCError` works in local network.
```bash
[2024-06-05 15:10:15 +0000] [204] [WARNING] [APP-LOG] Sent transaction has been already known: {'code': -32000, 'message': 'already known'} [in /app/ibet-Wallet-API/app/api/routers/eth.py:453]
```
=> Fix error handling of send_raw_transaction

app/config.py
For normal network usage, the current settings are too restrictive, so I think it would be better to increase the default values.
- `TXPOOL_THRESHOLD_FOR_TX_PAUSE`: 20 -> 200
=> Change the default value of TXPOOL_THRESHOLD_FOR_TX_PAUSE

app/api/routers/token.py, app/model/schema/base/__init__.py, app/model/schema/base/base.py, app/model/schema/token.py, tests/app/token_TransferHistory_test.py
- close #1544 
- Adding `created_from` and `created_to` query parameters to `GET: /Token/{token_address}/TransferHistory`
- Implementing a datetime string validator that:
- Accepts ISO 8601 format with timezone information
- Converts input to UTC
- Returns a consistent datetime format
- Updating the query builder to filter transfers based on the validated date range
- Introducing `ValidatedDatetimeStr` type for improved type checking
These changes align the GET endpoint's functionality with the existing `POST: /Token/{token_address}/TransferHistory/Search` endpoint, providing a consistent API experience for date range filtering across both methods.
=> [Feature]Add date range filtering to Transfer History API #1544

app/model/schema/base/base.py, app/model/schema/position.py, docs/ibet_wallet_api.yaml, migrations/env.py, tests/app/token_TransferHistory_test.py
- Resolve warnings in test output by addressing escape sequence issues.
- [actions log](https://github.com/BoostryJP/ibet-Wallet-API/actions/runs/10553595251/job/29234241892)
```bash
=============================== warnings summary ===============================
../../home/apl/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pydantic/fields.py:804
/home/apl/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pydantic/fields.py:804: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'nullable'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.7/migration/
warn(
tests/app/token_TransferHistory_test.py:950 …
```
=> Fix invalid escape sequence by using raw string

app/main.py, app/middleware/response_logger.py, app/middleware/strip_trailing_slash.py
- Refactored middlewares to avoid using `BaseHTTPMiddleware`.
=> Refactor middlewares to avoid using BaseHTTPMiddleware

app/api/routers/token.py, app/model/schema/token.py, docs/ibet_wallet_api.yaml, tests/app/token_TokenStatus_test.py
Close #1565 
- add `owner_address`  to `/{token_address}/Status` response
- `owner_address` is retrieved from `TokenList.getTokenByAddress`
=> feat: Allow fetching owner(issuer) address from /{token_address}/Status

app/model/db/__init__.py, app/model/db/idx_transfer.py, app/model/schema/token.py, batch/indexer_Transfer.py, migrations/versions/603fd86dc179_v24_12_0_feature_1574.py, tests/app/token_TransferHistory_Search_test.py, tests/app/token_TransferHistory_test.py, tests/batch/indexer_Transfer_test.py, tests/contract_modules.py
- Updated the data schema of lock/unlock contract event to classify transfer data derived from Unlock events
- Ref: https://github.com/BoostryJP/ibet-Prime/pull/713
=> Update data schema of lock/unlock event

Dockerfile, tests/Dockerfile_unittest
=> Upgrade ubuntu to 24.04

app/main.py, batch/__init__.py, batch/indexer_Block_Tx_Data.py, batch/indexer_CompanyList.py, batch/indexer_Consume_Coupon.py, batch/indexer_DEX.py, batch/indexer_Position_Bond.py, batch/indexer_Position_Coupon.py, batch/indexer_Position_Membership.py, batch/indexer_Position_Share.py, batch/indexer_Token_Detail.py, batch/indexer_Token_Detail_ShortTerm.py, batch/indexer_Token_Holders.py, batch/indexer_Token_List.py, batch/indexer_Transfer.py, batch/indexer_TransferApproval.py, batch/processor_Block_Sync_Status.py, batch/processor_Notifications_Coupon_Exchange.py, batch/processor_Notifications_Membership_Exchange.py, batch/processor_Notifications_Token.py, batch/processor_Send_Chat_Webhook.py, batch/processor_Send_Mail.py
When a Python process runs for an extended period, unused memory may not be released and returned to the OS. 
To address this, I have implemented periodic execution of `malloc_trim(0)` to free up unused heap memory as much as possible.
=> Release free memory back to the OS with malloc_trim

batch/indexer_CompanyList.py, batch/processor_Send_Chat_Webhook.py, pyproject.toml, tests/batch/indexer_CompanyList_test.py, tests/batch/processor_Send_Chat_Webhook_test.py, uv.lock
Currently, we use `httpx` as the HTTP client for batch processes. However, it has been reported that httpx may cause memory leaks in scenarios where a large number of clients are created.  
- https://github.com/encode/httpx/issues/978#issuecomment-819524210
In fact, in our project, we have observed a gradual increase in memory usage over time.  
This PR modifies the batch process to replace the `httpx` client with `aiohttp`. After switching to `aiohttp`, we have not observed any increasing memory usage trends.
None
- Replace HTTP Client for Batch Process to aiohttp
=> Change HTTP Client for Batch Process to aiohttp  

app/api/routers/admin.py, app/model/schema/admin.py, docs/ibet_wallet_api.yaml, tests/app/admin_Tokens_POST_test.py
In some cases, a normal response (returning token attributes) is preferred instead of a `409` error when adding a token. To accommodate this need, an option has been added to skip the `409` error during token addition.
- Related to #1609 
- Added an option to skip `ConflictError` when adding a token.
=> Add an option to skip `ConflictError` when adding a token

pyproject.toml, uv.lock
- Reverted web3.py from `7.8.0` to `7.5.0`
- web3.py `7.8.0` includes the following commit which could potentially generate excessive TLS connections in certain network configurations, so we're reverting to `7.5.0` which predates this change:
- https://github.com/ethereum/web3.py/commit/3b9c0f09553b2f30138285466a3b8fb8c62db600
- Related to #1593 
- Reverted web3.py to `7.5.0`
=> Revert web3.py to 7.5.0

.github/auto_assign.yml, .github/workflows/auto-assign.yml, .github/workflows/pr.yml
This pull request updates several GitHub Actions workflows to use more specific references for actions, ensuring better stability and traceability. The changes include pinning action versions to specific commit SHAs and updating to newer, more appropriate actions.
None
* [`.github/workflows/auto-assign.yml`](diffhunk://#diff-3df58dd42b351a284a19d2c3d3fe8c50db1cc811bb690ebbf402d1282bce9757L13-R13): Updated the `kentaro-m/auto-assign-action` to use a specific commit SHA (`f4648c0a9fdb753479e9e75fc251f507ce17bb7e`) instead of a version tag (`v2.0.0`).
* `.github/workflows/pr.yml`:
- Replaced `chartboost/ruff-action@v1` with `astral-sh/ruff-action@v3` to use the officially maintained action.
- Updated the `MishaKav/pytest-coverage-comment` action to pin it to a specific commit SHA …
=> Improve security for 3rd-party GH Actions

app/model/db/public_info.py, app/model/schema/public_info.py, docs/ibet_wallet_api.yaml
This pull request reduces the valid values for the `account_type` field across several files, limiting it to `1`, `2`, and `3` and removing `4` and `5`. These changes ensure consistency between the database model, schema, and API documentation.
None
* **Database model update**: In `app/model/db/public_info.py`, the `account_type` field in the `PublicAccountList` class now only accepts `Literal[1, 2, 3]`, removing `4` and `5` as valid options.
* **Schema update**: In `app/model/schema/public_info.py`, the `account_type` field in the `PublicAccount` class has been updated to match the new restriction of `Literal[1, 2, 3]`.
* **API documentation update**: In `docs/ibet_wallet_api.yaml`, the `account_type` component has been updated to remove `4` and `5` from the list of valid values.
=> Refactor account_type to limit values to 1, 2, and 3

batch/indexer_Position_Bond.py, batch/indexer_Position_Coupon.py, batch/indexer_Position_Membership.py, batch/indexer_Position_Share.py, batch/indexer_Transfer.py, batch/indexer_TransferApproval.py
This pull request introduces a safeguard across multiple indexer modules to handle cases where a token is not listed in the TokenList contract. The change ensures that such tokens are skipped gracefully, preventing potential errors or unnecessary processing.
- Related to #1640 
* Added a check in `__get_contract_list` methods across various indexer files (`batch/indexer_Position_Bond.py`, `batch/indexer_Position_Coupon.py`, `batch/indexer_Position_Membership.py`, `batch/indexer_Position_Share.py`, and `batch/indexer_TransferApproval.py`) to skip processing if a token type is `None`. This prevents errors when a token is not listed in the TokenList contract. [[1]](diffhunk://#diff-e6aee665fd2105ec8714613c9b50a178d710490eb24c89975f79782d6c70d9a8R249-R251) …
=> (v25.3) Skip processing for unlisted tokens in token type cache

app/model/db/public_info.py, app/model/schema/public_info.py, docs/ibet_wallet_api.yaml
This pull request introduces a new account type (`4`) to the system, updating the relevant database model, schema, and API documentation to ensure consistency across the application.
- Related to #1636 
* **Database model update:**
- Expanded the `account_type` field in `class PublicAccountList` to include `Literal[1, 2, 3, 4]`. (`app/model/db/public_info.py`, [app/model/db/public_info.pyL79-R79](diffhunk://#diff-32a542de7df291104133e7a8e214d1dc33bc5486d602f26e462055fcbea1797cL79-R79))
* **Schema update:**
- Updated the `account_type` field in `class PublicAccount` to include `Literal[1, 2, 3, 4]`. (`app/model/schema/public_info.py`, [app/model/schema/public_info.pyL54-R54](diffhunk://#diff-b8e5bdbf84c6017b002df4f3b0e606f540eef057d16bb331f9ce578aa8c01e41L54-R54))
* **API documentation …
=> Update account_type to include value 4 in PublicAccount model and API schema

batch/indexer_Company_List.py, batch/indexer_PublicInfo_PublicAccountList.py, batch/indexer_PublicInfo_TokenList.py, batch/processor_Send_Chat_Webhook.py, cmd/explorer/pyproject.toml, cmd/explorer/uv.lock, pyproject.toml, tests/batch/indexer_Company_List_test.py, tests/batch/indexer_PublicInfo_PublicAccountList_test.py, tests/batch/indexer_PublicInfo_TokenList_test.py, tests/batch/processor_Send_Chat_Webhook_test.py, uv.lock
- Replace aiohttp with requests
- Network connections through proxy configurations using HTTPS_PROXY environment variables don't function properly with aiohttp. To address this limitation, we're switching the HTTP client in specific batch processes to use requests instead.
- None
- Replaced aiohttp with requests in batch processing modules
=> Replace aiohttp with requests in batch processing modules

batch/indexer_Company_List.py, batch/indexer_PublicInfo_PublicAccountList.py, batch/indexer_PublicInfo_TokenList.py, batch/processor_Send_Chat_Webhook.py, cmd/explorer/pyproject.toml, cmd/explorer/uv.lock, pyproject.toml, tests/batch/indexer_Company_List_test.py, tests/batch/indexer_PublicInfo_PublicAccountList_test.py, tests/batch/indexer_PublicInfo_TokenList_test.py, tests/batch/processor_Send_Chat_Webhook_test.py, uv.lock
- Replace aiohttp with requests
- Network connections through proxy configurations using HTTPS_PROXY environment variables don't function properly with aiohttp. To address this limitation, we're switching the HTTP client in specific batch processes to use requests instead.
- Cherry pick from #1653 
- Replaced aiohttp with requests in batch processing modules
=> Replace aiohttp with requests in batch processing modules (25.9)

app/model/db/idx_transfer.py, app/model/schema/token.py, tests/batch/indexer_Transfer_test.py
This pull request introduces support for a new message type, `"ibet_wst_bridge"`, across the database models, schema, and test cases. The changes ensure consistent handling of this message type throughout the application.
- Related to #1647 
* Added `"ibet_wst_bridge"` to the `DataMessage` class in `app/model/db/idx_transfer.py` and `app/model/schema/token.py`. This expands the list of valid message types. [[1]](diffhunk://#diff-8004d43cd0ab067d85d3e2ef24ecd1ab7b07dc3d22f3766a557cbcdf105e33e8R50) [[2]](diffhunk://#diff-f4e88ec2faaf9af2e2935776f1749ab69fefaed04940ac5ce0d6933603961b46R431)
* Updated the `IDXTransfer` class in `app/model/db/idx_transfer.py` to include `"ibet_wst_bridge"` as a possible value for the `source_event` field.
* Added `"ibet_wst_bridge"` to the …
=> Update transfer tests and models to include 'ibet_wst_bridge' message

app/model/db/idx_transfer.py, app/model/schema/token.py, batch/indexer_Transfer.py, docs/ibet_wallet_api.yaml, tests/batch/indexer_Transfer_test.py, tests/contract_modules.py
This pull request introduces a new "Reallocation" transfer event type to the system, updates related models and schemas, and adds functionality to detect and handle this event during batch processing. It also includes tests to validate the new functionality.
- Close #1657 
* Added a new `REALLOCATION` event type to the `IDXTransferSourceEventType` and `TransferSourceEvent` enums in `app/model/db/idx_transfer.py` and `app/model/schema/token.py`. [[1]](diffhunk://#diff-8004d43cd0ab067d85d3e2ef24ecd1ab7b07dc3d22f3766a557cbcdf105e33e8R43) [[2]](diffhunk://#diff-f4e88ec2faaf9af2e2935776f1749ab69fefaed04940ac5ce0d6933603961b46R44-R45)
* Updated the `TransferHistory` and `TransferHistoriesResponse` models to include the new `REALLOCATION` event type. …
=> Add reallocation functionality to transfer process

app/model/db/__init__.py, app/model/db/idx_lock_unlock.py, app/model/db/idx_transfer.py, batch/indexer_Position_Bond.py, batch/indexer_Position_Share.py, batch/indexer_Transfer.py, migrations/versions/819325835c3d_v25_9_0_feature_1657.py, tests/batch/indexer_Position_Bond_test.py, tests/batch/indexer_Position_Share_test.py, tests/batch/indexer_Transfer_test.py, tests/migrations/upgrade_test.py
This pull request introduces new data models for lock and unlock messages, refactors existing code to use these models, and updates database migration and test cases accordingly. The changes aim to improve data validation and consistency across the system.
- Close #1657 
- Added `LockDataMessage` and `UnlockDataMessage` classes in `app/model/db/idx_lock_unlock.py` to define structured data models for lock and unlock messages using `pydantic` and `StrEnum`. [[1]](diffhunk://#diff-c893684e2e10ad7d92558365e56075adf8329acebb9bcaec1b7bdc6a1a7f775dR35-R54) [[2]](diffhunk://#diff-c893684e2e10ad7d92558365e56075adf8329acebb9bcaec1b7bdc6a1a7f775dL58-R80) [[3]](diffhunk://#diff-c893684e2e10ad7d92558365e56075adf8329acebb9bcaec1b7bdc6a1a7f775dL138-R160)
- Updated `IDXLock` and `IDXUnlock` models to …
=> Refactor lock and transfer data models to remove deprecated inheritance message

app/model/db/notification.py, batch/processor_Notifications_Token.py, tests/app/notification_Notifications_GET_test.py, tests/batch/processor_Notifications_Token_test.py, tests/contract_modules.py
This pull request introduces support for two new notification types, `ChangeToRedeemed` and `ChangeToCanceled`, and updates the notification processing system to handle these events. Additionally, it includes utility functions for testing these events in the contract modules.
- Close #1650 
* Added new notification types `CHANGE_TO_REDEEMED` and `CHANGE_TO_CANCELED` to the `NotificationType` enum in `app/model/db/notification.py`.
* Extended the `Watcher` class to support filtering by `token_type_list` and skipping past data during initial synchronization. [[1]](diffhunk://#diff-8a0136971d97939fea94c7295338b9ec2ba7cf41120ee6ed90ffa78dbbec145dL73-R88) [[2]](diffhunk://#diff-8a0136971d97939fea94c7295338b9ec2ba7cf41120ee6ed90ffa78dbbec145dL94-R118) …
=> Add watchers for ChangeToRedeemed and ChangeToCanceled events with notification processing

batch/indexer_Position_Bond.py, batch/indexer_Position_Coupon.py, batch/indexer_Position_Membership.py, batch/indexer_Position_Share.py, docs/ibet_wallet_api.yaml, tests/batch/indexer_Position_Bond_test.py, tests/batch/indexer_Position_Coupon_test.py, tests/batch/indexer_Position_Membership_test.py, tests/batch/indexer_Position_Share_test.py
Fix #1652 
Fix #1661
- Related to #1647 
* Simplified the condition in `__sink_on_position` methods across multiple files (`batch/indexer_Position_Bond.py`, `batch/indexer_Position_Coupon.py`, `batch/indexer_Position_Membership.py`, `batch/indexer_Position_Share.py`) by removing the `value > 0` check, leaving only `value is not None`. [[1]](diffhunk://#diff-e6aee665fd2105ec8714613c9b50a178d710490eb24c89975f79782d6c70d9a8L1860-R1860) [[2]](diffhunk://#diff-3eb449147237d15155e609df5e7356d468f22207a8e0951f0b7936578ef90192L947-R947) [[3]](diffhunk://#diff-f8682018d50b35d8077484e85c45e3b2f9cf7b36481f1235087c1df0b99113aaL911-R911) [[4]](diffhunk://#diff-7c8731c28bc19df2012ab5b9793f86eada370544630547f35c1d6e28938c5b34L1860-R1860)
* Added two new notification types, `ChangeToRedeemed` and …
=> Fix balance indexing

app/api/routers/notification.py, app/model/db/__init__.py, app/model/db/notification.py, app/model/schema/notification.py, batch/processor_Notifications_Coupon_Exchange.py, batch/processor_Notifications_Membership_Exchange.py, batch/processor_Notifications_Token.py, docs/ibet_wallet_api.yaml, migrations/versions/a5e395bf46a9_v25_9_0_feature_1662.py, tests/app/notification_NotificationsCount_test.py, tests/app/notification_NotificationsId_DELETE_test.py, tests/app/notification_NotificationsId_POST_test.py, tests/app/notification_NotificationsRead_test.py, tests/app/notification_Notifications_GET_test.py, tests/batch/processor_Notifications_Coupon_Exchange_test.py, tests/batch/processor_Notifications_Membership_Exchange_test.py, tests/batch/processor_Notifications_Token_test.py
This pull request introduces a new `notification_category` field to classify notifications by type, along with updates to the database schema, API, and batch processors to support this functionality. Additionally, it implements a Watcher to monitor changes to the `transferable` attribute of contracts.
- Close #1662 
* Added a new `notification_category` field to the `Notification` model to classify notifications as either "event_log" or "attribute_change" (`app/model/db/notification.py`).
* Introduced the `NotificationAttributeValue` model to store synchronized attribute values for notifications (`app/model/db/notification.py`).
* Updated the `NotificationType` enum to include new types for attribute change notifications (`app/model/db/notification.py`) …
=> Add notification category to Notification model and implement attribute change tracking watcher

package-lock.json, package.json, tests/batch/indexer_Transfer_test.py
This pull request makes a minor update to the version specification for the `hardhat` development dependency in `package.json`, changing it from a caret (`^`) to a tilde (`~`) to restrict updates to patch versions only.
None
- Bump hardhat: 2.26.2 -> 2.26.3
=> Update hardhat to version 2.26.3 and adjust versioning in package files

batch/indexer_Company_List.py, batch/indexer_PublicInfo_PublicAccountList.py, batch/indexer_PublicInfo_TokenList.py, tests/batch/indexer_Company_List_test.py, tests/batch/indexer_PublicInfo_PublicAccountList_test.py, tests/batch/indexer_PublicInfo_TokenList_test.py
This pull request refactors the way HTTP requests are made in the batch indexer modules to improve reliability and error handling. The main change is switching from direct `requests.get` calls to using a `requests.Session` with a configured `HTTPAdapter` and retry logic. Corresponding updates have been made to the test files to mock `requests.Session.get` instead of `requests.get`.
- Close #1674 
**HTTP request reliability improvements:**
* Updated `batch/indexer_Company_List.py`, `batch/indexer_PublicInfo_PublicAccountList.py`, and `batch/indexer_PublicInfo_TokenList.py` to use `requests.Session` with an `HTTPAdapter` and `Retry` for GET requests, enabling automatic retries on failure. [[1]](diffhunk://#diff-2359c2c901c0bf63f535536230a813892d80f729b49e09f624146375f560efccR27-R32) …
=> Add retry mechanism to HTTP requests in company_list/token_list/account_list indexer

uv.lock
Bump starlette from 0.46.2 to 0.47.3 and update revision in uv.lock
- None
- Bump starlette from 0.46.2 to 0.47.3 and update revision in uv.lock
- [-] I have added tests where necessary.
- [-] I have updated the documentation where necessary.
=> Bump starlette from 0.46.2 to 0.47.3 and update revision in uv.lock
