app/api/v2/position.py
app/api/v2/token.py
app/model/__init__.py
app/model/idx_transfer.py
app/tests/v2_position_couponmytokens_test.py
app/tests/v2_token_transferhistory_test.py
batch/indexer_Transfer.py

feat: rename model

---

app/model/token.py
app/tests/v2_company_companytokenlist_test.py
app/tests/v2_orderlist_test.py
app/tests/v2_position_sharemytokens_test.py
app/tests/v2_token_sharetokendetails_test.py
app/tests/v2_token_sharetokens_test.py
docs/ibet_wallet_api_v2.yaml

feat: add transfer_approval_required

---

bin/healthcheck_indexer.sh
bin/run_indexer.sh

Add to startup script

---

batch/indexer_TransferApproval.py

fix: argument error

---

batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py

- Changed the log output level of info and debug for the indexer process.

change log level

---

batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/processor_Notifications_Bond_Exchange.py
batch/processor_Notifications_Bond_Token.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Coupon_Token.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_PaymentGateway.py
batch/processor_Notifications_Share_Exchange.py
batch/processor_Notifications_Share_Token.py
conf/local.ini

fix #955 memory leak

---

CONTRIBUTING_ja.md
Dockerfile
app/tests/Dockerfile
docker-compose.yml

Support 10.15, the latest version of version 10 of postgreSQL.

Change postgres support target

---

app/api/v2/token.py
app/tests/v2_token_transferapprovalhistory_test.py
app/tests/v2_token_transferhistory_test.py

close #960
"Introduce pagination to TransferHistory and TransferApprovalHistory #960"

feat: 960 Add pagination to TransferApprovalHistory and TransferHistory

---

Dockerfile
app/tests/Dockerfile
batch/indexer_Transfer.py

close #986 
- hotfix: BulkTransfer does not output the transfer history

v21.4.1_beta1

---

batch/indexer_Transfer.py

fix: change naive to aware

---

app/api/v3/notification.py
app/main.py
app/tests/v3_notifications_GET_test.py
app/tests/v3_notifications_id_DELETE_test.py
docs/ibet_wallet_api_v3.yaml

feat: Add v3 notification API

---

app/api/v3/notification.py
app/main.py
app/tests/v3_notifications_GET_test.py
docs/ibet_wallet_api_v3.yaml

feat: Make account_address optional in v3.notification.Notifications

---

app/api/v2/position.py
app/api/v3/position.py
app/main.py
app/tests/v3_position_accountaddress_coupon_GET_test.py
app/tests/v3_position_accountaddress_coupon_contractaddress_GET_test.py
app/tests/v3_position_accountaddress_membership_GET_test.py
app/tests/v3_position_accountaddress_membership_contractaddress_GET_test.py
app/tests/v3_position_accountaddress_share_GET_test.py
app/tests/v3_position_accountaddress_share_contractaddress_GET_test.py
app/tests/v3_position_accountaddress_straightbond_GET_test.py
app/tests/v3_position_accountaddress_straightbond_contractaddress_GET_test.py
docs/ibet_wallet_api_v3.yaml

feat: v3 Position API

---

.github/workflows/test.yml
README.md
app/__init__.py
docs/ibet_wallet_api_v2.yaml
docs/ibet_wallet_api_v3.yaml

feat: add branching model

---

app/api/v2/nodeInfo.py
app/api/v3/e2e_message.py
app/main.py
docs/ibet_wallet_api_v2.yaml
docs/ibet_wallet_api_v3.yaml
tests/account_config.py
tests/app/v2_nodeinfo_test.py
tests/app/v3_e2e_message_encryptionkey_test.py
tests/conftest.py

feature: add e2e message encryption api

---

app/api/v3/events.py
app/main.py
docs/ibet_wallet_api_v3.yaml
tests/app/v3_events_e2emessaging_test.py

feat: add E2EMassaging event search api

---

app/api/v3/events.py
app/main.py
docs/ibet_wallet_api_v3.yaml
tests/app/v3_e2e_message_encryptionkey_test.py
tests/app/v3_events_e2emessaging_test.py
tests/app/v3_events_ibetescrow_test.py
tests/conftest.py
tests/utils/__init__.py
tests/utils/standard_token.py

feat: add contract event api

---

app/config.py
batch/processor_Block_Sync_Status.py

feat: variable threshold for block synchronisation monitoring

---

app/api/v2/token.py
docs/ibet_wallet_api_v2.yaml
tests/app/v2_token_tokenstatus_test.py

feat: Add token type

---

app/api/common/base.py
app/errors.py
app/main.py
app/middleware/session_manager.py
app/middleware/translator.py
requirements.txt
tests/conftest.py

close #1056
refs
https://falcon.readthedocs.io/en/stable/changes/2.0.0.html
https://falcon.readthedocs.io/en/stable/changes/3.0.0.html

feat: upgrade falcon

---

app/api/v2/order_list.py
docs/ibet_wallet_api_v2.yaml
tests/app/v2_orderlist_test.py

feat: return order cancel items

---

batch/indexer_CompanyList.py
tests/batch/indexer_CompanyList_test.py

fix: include null homepage

---

app/api/v2/market_information.py
docs/ibet_wallet_api_v2.yaml
tests/app/v2_marketinformation_couponorderbook_test.py
tests/app/v2_marketinformation_membershiporderbook_test.py
tests/app/v2_marketinformation_straightbondorderbook_test.py

feat: Add the exchange address to the return field

---

app/api/v2/token.py
app/model/db/idx_transfer_approval.py
batch/indexer_TransferApproval.py
migrations/versions/024_alter_transfer_approval.py
tests/app/v2_token_transferapprovalhistory_test.py
tests/batch/indexer_TransferApproval_test.py
tests/conftest.py
tests/contract_modules.py

feat: indexing approval events within IbetEscrow

---

app/api/v2/admin.py
app/api/v2/company.py
app/api/v2/eth.py
app/api/v2/market_information.py
app/api/v2/order_list.py
app/api/v2/position.py
app/api/v2/statistics.py
app/api/v2/token.py
app/api/v2/user.py
app/api/v3/e2e_message.py
app/api/v3/position.py
app/contracts/contract.py
app/model/blockchain/token.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/lib/token.py
batch/lib/token_list.py
batch/processor_Notifications_Token.py
docs/ibet_wallet_api_v2.yaml
docs/ibet_wallet_api_v3.yaml
tests/app/v2_position_straightbondmytokens_test.py
tests/app/v3_position_accountaddress_straightbond_GET_test.py
tests/app/v3_position_accountaddress_straightbond_contractaddress_GET_test.py

feat: backward compatible function call

---

app/contracts/contract.py

- Fixed error handling for BadFunctionCallOutput only

feat: more detailed error handling

---

app/api/v2/statistics.py
app/api/v2/token.py
app/model/db/idx_position.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
docs/ibet_wallet_api_v2.yaml
migrations/versions/025_alter_position.py
tests/app/v2_statistics_token_test.py
tests/app/v2_token_tokenholders_test.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py
tests/contract_modules.py

feat: add volume about exchange

---

app/api/v2/eth.py
app/model/db/idx_transfer_approval.py
batch/indexer_TransferApproval.py

fix: add missing field

---

README.md
docker-compose.yml

feat: upgrade PostgreSQL

---

app/api/v3/events.py
tests/app/v3_events_e2emessaging_test.py
tests/app/v3_events_ibetescrow_test.py
tests/app/v3_events_ibetsecuritytokenescrow_test.py

feat: return block_timestamp

---

app/api/v2/market_information.py
tests/app/v2_marketinformation_couponorderbook_test.py
tests/app/v2_marketinformation_membershiporderbook_test.py
tests/app/v2_marketinformation_straightbondorderbook_test.py

hotfix: Fixed orderbook error when cancelling an agreement

---

app/config.py
bin/run_processor_notification.sh

Token notification is now optional.

feat: Make token notification optional

---

batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py

fix: Fix a bug that cause an Error from the indexer when making a new order

---

batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/processor_Notifications_Token.py
tests/batch/processor_Notifications_Token_test.py
tests/contract_modules.py

hotfix: Fixed a bug that caused unneeded data to be registered in the database when upgrading IbetExchange

---

batch/processor_Notifications_Bond_Token.py
batch/processor_Notifications_Coupon_Token.py
batch/processor_Notifications_Share_Token.py
tests/batch/processor_Notifications_Bond_Token_test.py
tests/batch/processor_Notifications_Coupon_Token_test.py
tests/batch/processor_Notifications_Share_Token_test.py
tests/contract_modules.py

fix: Notification registration is also skipped when upgrading DEX

---

batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/processor_Notifications_Bond_Exchange.py
batch/processor_Notifications_Bond_Token.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Coupon_Token.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_PaymentGateway.py
batch/processor_Notifications_Share_Exchange.py
batch/processor_Notifications_Share_Token.py

fix: Add exception handling when web3 is not available

---

app/api/v2/admin.py
app/api/v2/position.py
app/api/v3/position.py
docs/ibet_wallet_api_v2.yaml
docs/ibet_wallet_api_v3.yaml
tests/app/v3_position_accountaddress_coupon_GET_test.py
tests/app/v3_position_accountaddress_membership_GET_test.py
tests/app/v3_position_accountaddress_share_GET_test.py
tests/app/v3_position_accountaddress_straightbond_GET_test.py

deprecated v2 postion API

---

batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/processor_Block_Sync_Status.py
batch/processor_Notifications_Bond_Exchange.py
batch/processor_Notifications_Bond_Token.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Coupon_Token.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_PaymentGateway.py
batch/processor_Notifications_Share_Exchange.py
batch/processor_Notifications_Share_Token.py

#1111
- v21.9
- refactor error handling

Refactor error handling

---

batch/indexer_CompanyList.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/processor_Block_Sync_Status.py
batch/processor_Notifications_Bond_Exchange.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Share_Exchange.py
batch/processor_Notifications_Token.py
tests/batch/indexer_CompanyList_test.py
tests/batch/indexer_Consume_Coupon_test.py
tests/batch/indexer_DEX_test.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py
tests/batch/indexer_TransferApproval_test.py
tests/batch/indexer_Transfer_test.py
tests/batch/processor_Block_Sync_Status_test.py
tests/batch/processor_Notifications_Token_test.py

fix: Failover fails

---

app/database/__init__.py
app/utils/web3_utils.py
tests/app/v2_eth_sendrawtransaction_test.py
tests/app/v2_nodeinfo_blocksyncstatus_test.py
tests/conftest.py

Avoid DB connection error when restarting a worker

---

app/database/__init__.py
app/utils/web3_utils.py
tests/app/v2_eth_sendrawtransaction_test.py
tests/app/v2_nodeinfo_blocksyncstatus_test.py
tests/conftest.py

Cherry-pick #1116 (v21.12)

---

app/database/__init__.py
app/utils/web3_utils.py
tests/app/v2_eth_sendrawtransaction_test.py
tests/app/v2_nodeinfo_blocksyncstatus_test.py
tests/conftest.py

Cherry-pick #1116 (v22.3)

---

app/database/__init__.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/processor_Block_Sync_Status.py
batch/processor_Notifications_Bond_Exchange.py
batch/processor_Notifications_Bond_Token.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Coupon_Token.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_PaymentGateway.py
batch/processor_Notifications_Share_Exchange.py
batch/processor_Notifications_Share_Token.py

fix: pool_pre_ping True

---

app/database/__init__.py
batch/indexer_CompanyList.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/processor_Block_Sync_Status.py
batch/processor_Notifications_Bond_Exchange.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Share_Exchange.py
batch/processor_Notifications_Token.py

fix: pool_pre_ping True (v22.3)

---

.gitignore
app/api/v3/events.py
docs/ibet_wallet_api_v3.yaml
tests/app/v3_events_e2emessaging_test.py
tests/app/v3_events_ibetescrow_test.py
tests/app/v3_events_ibetsecuritytokenescrow_test.py

feat: add search condition of indexed parameter to Event API

---

app/api/v2/token.py
docs/ibet_wallet_api_v2.yaml
tests/app/v2_token_coupontokendetails_test.py
tests/app/v2_token_coupontokens_test.py
tests/app/v2_token_membershiptokendetails_test.py
tests/app/v2_token_membershiptokens_test.py
tests/app/v2_token_sharetokendetails_test.py
tests/app/v2_token_sharetokens_test.py
tests/app/v2_token_straightbondtokendetails_test.py
tests/app/v2_token_straightbondtokens_test.py

feat: get tokens with status False

---

app/contracts/contract.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
tests/batch/indexer_Consume_Coupon_test.py
tests/batch/indexer_DEX_test.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py
tests/batch/indexer_TransferApproval_test.py
tests/batch/indexer_Transfer_test.py

fix: [BUG] processing block is skipped when web3 service is not available during Indexer execution

---

batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Token_Holders.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
tests/batch/indexer_Consume_Coupon_test.py
tests/batch/indexer_DEX_test.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py
tests/batch/indexer_Token_Holders_test.py
tests/batch/indexer_TransferApproval_test.py
tests/batch/indexer_Transfer_test.py

fix: [BUG] processing block is skipped when web3 service is not available during Indexer execution(dev-22.6)

---

batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
tests/batch/indexer_Consume_Coupon_test.py
tests/batch/indexer_DEX_test.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py
tests/batch/indexer_TransferApproval_test.py
tests/batch/indexer_Transfer_test.py

fix: [BUG] processing block is skipped when web3 service is not available during Indexer execution(dev-21.9)

---

app/contracts/contract.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
tests/batch/indexer_Consume_Coupon_test.py
tests/batch/indexer_DEX_test.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py
tests/batch/indexer_TransferApproval_test.py
tests/batch/indexer_Transfer_test.py

fix: [BUG] processing block is skipped when web3 service is not available during Indexer execution(dev-21.12)

---

app/model/db/__init__.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py

fix: module import error

---

migrations/versions/029_create_token_holder.py
migrations/versions/030_create_idx_position_bond_block_number.py
migrations/versions/031_create_idx_position_share_block_number.py
migrations/versions/032_create_idx_position_membership_block_number.py
migrations/versions/033_create_idx_position_coupon_block_number.py

add migration script

---

README.md
app/api/v2/eth.py
docker-compose.yml
tests/app/v2_eth_sendrawtransactionnowait_test.py

feat: upgrade ganache

---

app/model/db/idx_position.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
migrations/versions/030_create_idx_position_bond_block_number.py
migrations/versions/031_create_idx_position_share_block_number.py
migrations/versions/032_create_idx_position_membership_block_number.py
migrations/versions/033_create_idx_position_coupon_block_number.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py

fix: Unlisted token may be skipped in position Indexer after it changes to be listed

---

app/model/db/idx_position.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
migrations/versions/030_create_idx_position_bond_block_number.py
migrations/versions/031_create_idx_position_share_block_number.py
migrations/versions/032_create_idx_position_membership_block_number.py
migrations/versions/033_create_idx_position_coupon_block_number.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py

[FEATURE] Position indexer batch improvements

---

README.md
app/model/blockchain/token.py
docker-compose.yml

feat: update company information in the cache

---

batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
docs/ibet_wallet_api_v2.yaml
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py

fix: Cursor number is overwritten by a number lower than the start number in Position indexer

---

README.md
app/config.py
app/database/__init__.py
app/middleware/session_manager.py
app/utils/web3_utils.py
docker-compose.yml
tests/conftest.py
tests/qa.sh

fix: Data may be updated if API had operated with DB and failed in logic

---

batch/indexer_CompanyList.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Token_Holders.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py

fix: Remove redundant exception logs in batches

---

app/api/v2/token.py
app/api/v3/token.py
app/main.py
app/model/blockchain/token.py
docs/ibet_wallet_api_v2.yaml
docs/ibet_wallet_api_v3.yaml
tests/app/v3_token_coupontokenaddresses_test.py
tests/app/v3_token_coupontokens_test.py
tests/app/v3_token_membershiptokenaddresses_test.py
tests/app/v3_token_membershiptokens_test.py
tests/app/v3_token_sharetokenaddresses_test.py
tests/app/v3_token_sharetokens_test.py
tests/app/v3_token_straightbondtokenaddresses_test.py
tests/app/v3_token_straightbondtokens_test.py

add: add result_set for pagination when getting token list

---

app/api/v2/admin.py
tests/app/v2_admin_Token_DELETE_test.py
tests/app/v2_admin_Token_POST_test.py

fix: integrity error

---

bin/run_server.sh

close #1178 
Changed the limit_request_line setting for gunicorn to unlimited.

feat: unlimited request line size

---

app/api/v2/token.py
app/model/db/tokenholders.py
batch/indexer_Token_Holders.py
docs/ibet_wallet_api_v2.yaml
tests/batch/indexer_Token_Holders_test.py

fix: Some attributes in the token holder model do not match the db columns

---

app/api/v2/token.py
app/main.py
docs/ibet_wallet_api_v2.yaml
tests/app/v2_token_tokenholders_count_test.py

Close #1187 
- GET: `/v2/Token/{contract_address}/Holders/Count`

feat: add API to get the number of holders

---

app/api/v3/position.py
app/model/blockchain/token.py
app/model/db/__init__.py
app/model/db/idx_token.py
batch/indexer_Token_Detail_ShortTerm.py
docs/ibet_wallet_api_v3.yaml
tests/app/v3_position_accountaddress_coupon_GET_test.py
tests/app/v3_position_accountaddress_membership_GET_test.py
tests/app/v3_position_accountaddress_share_GET_test.py
tests/app/v3_position_accountaddress_straightbond_GET_test.py

feat: add query parameter for enabling index to v3 position API

---

README.md
README_JA.md

feat: add Japanese README

---

bin/run_server.sh

fix: remove reload option on running gunicorn

---

app/api/routers/eth.py
tests/app/eth_SendRawTransaction_test.py

fix: logging level of contract revert log

---

requirements.lock
tests/app/token_TokenHoldersCollectionid_test.py

https://github.com/BoostryJP/ibet-Wallet-API/pull/1203

fix: timeout/poll_latency value of wait for transaction receipt in SendRawTransaction API

---

app/api/routers/eth.py
app/config.py
tests/app/eth_SendRawTransaction_test.py

cherry-pick from #1203

---

app/api/routers/eth.py
app/model/schema/eth.py
tests/app/eth_SendRawTransaction_test.py

- Add transaction hash to /Eth/SendRawTransaction return

feat: Add transaction hash to return

---

batch/indexer_Token_Detail_ShortTerm.py

Fix: 1170
- Change the interval of commit in Token Detail Short-Term indexer.
- Remove update statement of created in Token Detail Short-Term indexer.

Fix: short term cache

---

batch/indexer_Token_Detail_ShortTerm.py

cherry-pick from #1209

---

requirements.lock
requirements.txt
tests/app/eth_SendRawTransactionNowait_test.py
tests/app/eth_SendRawTransaction_test.py
tests/app/eth_WaitForTransactionReceipt_test.py
tests/batch/indexer_Consume_Coupon_test.py
tests/batch/indexer_DEX_test.py
tests/batch/indexer_Transfer_test.py
tests/batch/processor_Block_Sync_Status_test.py
tests/loadtest/locustfile.py

- Upgrade web3py to latest version

feat: Upgrade web3py

---

app/model/db/__init__.py
app/model/db/idx_transfer.py
batch/indexer_Transfer.py
migrations/versions/041_create_idx_transfer_block_number.py
tests/batch/indexer_Transfer_test.py

feat: skip synchronized blocks

---

app/model/db/__init__.py
app/model/db/idx_transfer.py
batch/indexer_Transfer.py
migrations/versions/041_create_idx_transfer_block_number.py
tests/batch/indexer_Transfer_test.py

cherry pick from #1214

---

batch/indexer_Transfer.py
tests/batch/indexer_Transfer_test.py

fix: skip logic of transfer indexer batch

---

batch/indexer_Transfer.py
tests/batch/indexer_Transfer_test.py

remove: to_timestamp in indexer transfer batch

---

batch/indexer_Transfer.py
tests/batch/indexer_Transfer_test.py

Cherry pick from #1217 / #1218

Cherry pick from #1217 / #1218

---

app/model/blockchain/token.py
app/model/schema/token_share.py
docs/ibet_wallet_api.yaml
tests/app/company_info_CompanyTokenList_test.py
tests/app/dex_orderlist_test.py
tests/app/position_PositionShareContractAddress_test.py
tests/app/position_PositionShare_test.py
tests/app/token_share_ShareTokenDetails_test.py
tests/app/token_share_ShareTokens_test.py
tests/batch/indexer_Token_Detail_ShortTerm_test.py
tests/batch/indexer_Token_Detail_test.py

feat: Extend the number of decimal places of dividends to 13

---

docker-compose.yml

Supported postgresql version upgrades

feat: support postgresql 13.8

---

app/api/routers/eth.py
app/model/schema/__init__.py
app/model/schema/eth.py
docs/ibet_wallet_api.yaml
tests/app/eth_WaitForTransactionReceipt_test.py

feat: Change HTTP method of WaitForTransactionReceipt to GET

---

app/main.py

Add API Root path for process health check.
root path was removed in below commit/PR.
commit: 6d4344657550430143b06276476a54202f1587b8
PR: https://github.com/BoostryJP/ibet-Wallet-API/pull/1224

add: root path for process health check

---

app/contracts/contract.py

feat: Add exception handling for backward compatible function call

---

app/config.py
tests/app/config_test.py
tests/app/dex_market_CouponOrderBook_test.py
tests/app/dex_market_MembershipOrderBook_test.py
tests/app/dex_market_StraightBondOrderBook_test.py

fix: TRANSACTION_WAIT_POLL_LATENCY restriction(dev-22.9)

---

app/config.py
tests/app/config_test.py
tests/app/dex_market_CouponOrderBook_test.py
tests/app/dex_market_MembershipOrderBook_test.py
tests/app/dex_market_StraightBondOrderBook_test.py

fix: TRANSACTION_WAIT_POLL_LATENCY restriction(dev-22.12)

---

batch/indexer_Token_Detail.py
batch/indexer_Token_Detail_ShortTerm.py

(cherry picked from commit f1f32d05539716f9e8ea4fc2400cd11d585a37aa)

fix: add ObjectDeletedError handling (for v22.9)

---

batch/processor_Notifications_Bond_Exchange.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Share_Exchange.py
batch/processor_Notifications_Token.py

I deleted the unused variable because it was left behind.

fix: Delete unused variables

---

requirements.lock

feat: Update sqlalchemy

---

app/model/blockchain/token.py

feat: Cache memo

---

app/contracts/contract.py
app/model/blockchain/token.py
tests/app/company_info_CompanyTokenList_test.py
tests/app/dex_orderlist_test.py
tests/app/position_PositionShareContractAddress_test.py
tests/app/position_PositionShare_test.py
tests/app/token_share_ShareTokenDetails_test.py
tests/app/token_share_ShareTokens_test.py
tests/batch/indexer_Token_Detail_ShortTerm_test.py
tests/batch/indexer_Token_Detail_test.py

apply changes of PR #1220 and #1230 to v22.9 as hotfix

fix: the number of decimal places of dividends to 13(v22.9)

---

app/contracts/contract.py
app/model/blockchain/token.py
tests/app/v2_company_companytokenlist_test.py
tests/app/v2_orderlist_test.py
tests/app/v2_position_sharemytokens_test.py
tests/app/v2_token_sharetokendetails_test.py
tests/app/v2_token_sharetokens_test.py
tests/app/v3_position_accountaddress_share_GET_test.py
tests/app/v3_position_accountaddress_share_contractaddress_GET_test.py

apply changes of PR #1220 and #1230 to v22.6 as hotfix

fix: the number of decimal places of dividends to 13(v22.6)

---

app/contracts/contract.py
app/model/blockchain/token.py
tests/app/v2_company_companytokenlist_test.py
tests/app/v2_orderlist_test.py
tests/app/v2_position_sharemytokens_test.py
tests/app/v2_token_sharetokendetails_test.py
tests/app/v2_token_sharetokens_test.py
tests/app/v3_position_accountaddress_share_GET_test.py
tests/app/v3_position_accountaddress_share_contractaddress_GET_test.py

apply changes of PR #1220 and #1230 to v22.3 as hotfix

fix: the number of decimal places of dividends to 13(v22.3)

---

bin/run_indexer.sh
bin/run_server.sh

[FEATURE] Add warning message if company_list.json is empty with `COMPANY_LIST_LOCAL_MODE` = 1

---

app/config.py
tests/batch/processor_Block_Sync_Status_test.py

feat: change the default value of `BLOCK_SYNC_REMAINING_THRESHOLD`

---

app/model/db/__init__.py
app/model/db/idx_token_list.py
app/model/db/idx_transfer.py
app/model/db/notification.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Token.py
migrations/versions/042_create_notification_block_number.py
tests/batch/processor_Notifications_Coupon_Exchange_test.py
tests/batch/processor_Notifications_Membership_Exchange_test.py
tests/batch/processor_Notifications_Token_test.py

feat: Notification processor improvements

---

batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Token.py
tests/batch/processor_Notifications_Coupon_Exchange_test.py
tests/batch/processor_Notifications_Membership_Exchange_test.py
tests/batch/processor_Notifications_Token_test.py

Related to: #1261 
Fixed an error in the logic for cases where no event occurred.

fix: Notification processor improvements

---

app/api/routers/token.py
app/model/schema/__init__.py
app/model/schema/token.py
docs/ibet_wallet_api.yaml
tests/app/token_TokenHoldersCount_test.py
tests/app/token_TokenHolders_test.py

Close #1259 
- added query flag to GET: `/{token_address}/Holders/Count`

feat: Add query param to holder count API for excluding issuer

---

app/api/routers/admin.py
tests/app/admin_Tokens_POST_test.py

Close #1260 
- implemented a logic to get owner position in POST: `/Admin/Tokens`

feat: get owner position with POST: `/Admin/Tokens` API

---

app/api/routers/eth.py

Related to #1227
- Fixed timeout query.
- Specify exception raised by `wait_for_transaction_receipt`

fix: query of WaitForTransactionReceipt

---

ENV_LIST.md
app/config.py
app/model/db/__init__.py
app/model/db/idx_block_data.py
app/model/db/idx_tx_data.py
batch/indexer_Block_Tx_Data.py
bin/healthcheck_indexer.sh
bin/run_indexer.sh
migrations/versions/043_create_block_data.py
migrations/versions/044_create_idx_block_data_block_number.py
migrations/versions/045_create_tx_data.py
tests/batch/indexer_Block_Tx_Data_test.py

#1267 
- Add Indexer for indexing BlockData and TxData.
- New environment variable: BC_EXPLORER_ENABLED (default: 0)

feat: Add BC Explorer indexer

---

batch/processor_Notifications_Token.py
tests/batch/processor_Notifications_Token_test.py

feat: remove unnecessary I/O request in Token Notification batch

---

batch/indexer_Block_Tx_Data.py
batch/indexer_CompanyList.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Token_Detail.py
batch/indexer_Token_Detail_ShortTerm.py
batch/indexer_Token_Holders.py
batch/indexer_Token_List.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Token.py
tests/batch/indexer_Block_Tx_Data_test.py
tests/batch/indexer_Consume_Coupon_test.py
tests/batch/indexer_DEX_test.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py
tests/batch/indexer_Token_Holders_test.py
tests/batch/indexer_TransferApproval_test.py

- Removed unnecessary output.
- Improved log output at process `start` and `completed` timing.

feat: Improve batch log output

---

app/config.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Token.py

- Clean up config.py
- Increase notification process interval to 60 seconds

feat: Increase notification interval

---

app/api/routers/admin.py
app/api/routers/token.py
tests/app/admin_Token_DELETE_test.py
tests/app/notification_NotificationsId_DELETE_test.py

fix: deletion not committed in DELETE: `/Tokens/{token_address}`

---

README.md
README_JA.md

doc: Add an explanation on how to reference the API documentation

---

README.md
README_JA.md
bin/healthcheck_processor.sh
bin/healthcheck_server.sh
bin/run_processor.sh
bin/run_server.sh
healthcheck.sh
run.sh

feat: Start block synchronous monitoring process in batch mode

---

batch/processor_Block_Sync_Status.py
tests/batch/processor_Block_Sync_Status_test.py

feat: Delete remaining past WEB3_HTTP_PROVIDER data

---

app/api/routers/token.py
tests/app/token_TokenHoldersCount_test.py
tests/app/token_TokenHolders_test.py

fix: add query filter of token_address to token holder API

---

app/utils/web3_utils.py

feat: add HTTPError handling to web3_utils

---

batch/processor_Send_Mail.py
tests/batch/processor_Send_Mail_test.py

fix: Fixed error handling when sending e-mail

---

batch/indexer_Token_Holders.py
tests/batch/indexer_Token_Holders_test.py

fix: requests.exceptions.ReadTimeout occurs in indexer of Token Holders

---

app/api/routers/admin.py
app/api/routers/bc_explorer.py
app/api/routers/company_info.py
app/api/routers/contract_abi.py
app/api/routers/dex_market.py
app/api/routers/dex_order_list.py
app/api/routers/e2e_message.py
app/api/routers/eth.py
app/api/routers/events.py
app/api/routers/node_info.py
app/api/routers/notification.py
app/api/routers/position.py
app/api/routers/token.py
app/api/routers/token_bond.py
app/api/routers/token_coupon.py
app/api/routers/token_membership.py
app/api/routers/token_share.py
app/api/routers/user_info.py
app/config.py
app/model/schema/base.py
app/utils/fastapi.py
docker-compose.yml
requirements.lock
requirements.txt

- It was discovered that response validation produce errors in environments where past data or unexpected data structure remained or when.
- So we made a hotfix to disable response validation in production mode, as in v23.3 and later versions.

hotfix: Remove response validation

---

app/api/routers/position.py
app/api/routers/token.py
app/api/routers/token_bond.py
app/api/routers/token_coupon.py
app/api/routers/token_membership.py
app/api/routers/token_share.py

cherry pick from #1324

---

Dockerfile
cmd/explorer/poetry.lock
cmd/explorer/pyproject.toml

fix: dependent packages install order

---

batch/indexer_Token_Holders.py
tests/batch/indexer_Token_Holders_test.py

Close: #1330 
- Added `argument_filter` to getLogs function in `indexer_Token_Holders.py`.

feat: add argument filter to indexer batch

---

app/api/routers/bc_explorer.py
app/api/routers/node_info.py
app/api/routers/notification.py
app/api/routers/position.py
app/api/routers/token.py
app/config.py
cmd/explorer/poetry.lock
cmd/explorer/pyproject.toml
docker-compose.yml
requirements.txt

Related to: #1338 , #1318, #1126

downgrade sqlalchemy and psycopg

---

app/api/routers/bc_explorer.py
cmd/explorer/src/gui/screen/block.py
cmd/explorer/src/gui/widget/query_panel.py
cmd/explorer/src/main.py
tests/app/node_info_ListBlockData_test.py

Close: #1340
- modified the logic of total count about block data

feat: modify total count of block data list

---

app/api/routers/position.py
app/model/schema/position.py
docs/ibet_wallet_api.yaml
tests/app/position_PositionShare_Lock_Event_GET_test.py
tests/app/position_PositionStraightBond_Lock_Event_GET_test.py

feat: Replace token_address with token_address_list in lock event API query

---

batch/indexer_Token_Holders.py
tests/batch/indexer_Token_Holders_test.py

fix: avoid storing non-holders in TokenHolders batch

---

ENV_LIST.md
app/api/routers/position.py
app/config.py
batch/indexer_Token_Detail.py
batch/indexer_Token_Detail_ShortTerm.py
batch/indexer_Token_List.py
conf/local.ini
docker-compose.yml
tests/app/position_PositionShare_Lock_Event_GET_test.py
tests/app/position_PositionShare_Lock_test.py
tests/app/position_PositionShare_test.py
tests/app/position_PositionStraightBond_Lock_Event_GET_test.py
tests/app/position_PositionStraightBond_Lock_test.py
tests/app/position_PositionStraightBond_test.py
tests/app/token_bond_StraightBondTokenAddresses_test.py
tests/app/token_bond_StraightBondTokens_test.py
tests/app/token_coupon_CouponTokenAddresses_test.py
tests/app/token_coupon_CouponTokens_test.py
tests/app/token_membership_MembershipTokenAddresses_test.py
tests/app/token_membership_MembershipTokens_test.py
tests/app/token_share_ShareTokenAddresses_test.py
tests/app/token_share_ShareTokens_test.py
tests/batch/indexer_Token_Detail_ShortTerm_test.py
tests/batch/indexer_Token_Detail_test.py
tests/batch/indexer_Token_List_test.py

Change the default value of TOKEN_ENABLED to False

---

app/api/routers/position.py
tests/app/position_PositionShare_Lock_test.py

feat: exclude 0 value record from locked position API response

---

app/api/routers/eth.py
app/main.py
app/model/schema/__init__.py
app/model/schema/eth.py
docs/ibet_wallet_api.yaml
tests/app/eth_EthereumJsonRpc_test.py

Add raw eth json rpc endpoint

---

README.md
README_JA.md
app/model/db/base.py
docker-compose.yml
poetry.lock
pyproject.toml
tests/app/token_Lock_test.py

- Change MySQL version to support
- Change minor version of PostgreSQL used in unit test
- Misc: Update 3rd party libraries

Bump DB version

---

poetry.lock
pyproject.toml

Bump web3.py version

---

tests/conftest.py

Improve unit test performance

---

tests/conftest.py

fix unit test conf

---

migrations/env.py

- Added migration completion message.
- If migration is completed successfully, you can see `[INFO] Successfully completed.` in console.

Add migration completion message

---

app/api/routers/token_bond.py
app/api/routers/token_coupon.py
app/api/routers/token_membership.py
app/api/routers/token_share.py
batch/indexer_Token_Detail.py

Fix DB commit unit in indexer_Token_Detail batch

---

app/api/routers/bc_explorer.py
app/api/routers/node_info.py
app/utils/web3_utils.py
docs/ibet_wallet_api.yaml
tests/app/node_info_BlockSyncStatus_test.py

utils: Dynamically set the Quorum connection timeout

---

app/model/db/notification.py
migrations/versions/ae65533fdc41_v23_9_0_feature_1411.py

model: Add index to notification TBL

---

batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Token.py

Add mismatched abi error handling

---

batch/indexer_Token_Detail.py
batch/indexer_Token_Detail_ShortTerm.py

Remove unnecessary WHERE clauses so as to fetch detailed information of all tokens as a cache

---

.github/workflows/codeql-analysis.yml
.github/workflows/pr.yml
.pre-commit-config.yaml
poetry.lock
pyproject.toml

- Change psycopg installation option to psycopg-c
- Updated 3rd-party libraries.

Change to psycopg-c

---

batch/indexer_Block_Tx_Data.py
poetry.lock
pyproject.toml

Upgrade web3py to the latest version.

Bump web3py

---

README.md
README_JA.md
docker-compose.yml

Support PostgreSQL 15

---

app/api/routers/token.py
app/model/schema/__init__.py
app/model/schema/base/__init__.py
app/model/schema/base/base.py
app/model/schema/token.py
docs/ibet_wallet_api.yaml
poetry.lock
pyproject.toml
tests/app/token_TransferApprovalHistory_Search_test.py
tests/app/token_TransferApprovalHistory_test.py
tests/app/token_TransferHistory_Search_test.py
tests/app/token_TransferHistory_test.py

Add search filter and sort to transfer / transfer approval list API

---

app/api/routers/token.py
app/model/schema/token.py
docs/ibet_wallet_api.yaml
tests/app/token_TokenHolders_Search_test.py
tests/app/token_TokenHolders_test.py

Related to https://github.com/BoostryJP/ibet-Wallet-API/pull/1438

Add search filter to token holders API

---

app/api/routers/admin.py
app/model/db/company.py
app/model/db/idx_lock_unlock.py
app/model/db/idx_position.py
app/model/db/idx_transfer.py
app/model/db/listing.py
app/model/db/notification.py
migrations/versions/a70bd06d34a7_v23_12_0_feature_1451.py

Add SQL INDEX to columns which frequently used in sort

---

app/model/db/company.py
migrations/versions/f6f13d28bb48_v23_12_0_feature_1454.py

Add covering index for company table

---

app/api/routers/dex_market.py
app/api/routers/dex_order_list.py
app/api/routers/notification.py
app/api/routers/position.py
app/model/db/idx_transfer.py
app/model/db/idx_transfer_approval.py
app/model/db/listing.py
app/model/db/notification.py
cmd/explorer/src/gui/widget/block_list_view.py

According to our research, `strftime` is slow and can be a bottleneck when processing large amounts of data.
I fixed to speed up processing by not using `strftime`.

Speed up strftime

---

cmd/explorer/pyproject.toml
cmd/explorer/src/gui/explorer.css
cmd/explorer/src/gui/screen/block.py
cmd/explorer/src/gui/screen/transaction.py
cmd/explorer/src/gui/widget/block_list_table.py
cmd/explorer/src/gui/widget/menu.py
cmd/explorer/src/gui/widget/query_panel.py
cmd/explorer/src/gui/widget/tx_list_table.py
poetry.lock
pyproject.toml

Close: #1452 
- Some APIs on Textual have been changed, so the bc-explorer code has been updated accordingly.
- I have tested bc-explorer on terminal.

Bump textual

---

Dockerfile
tests/Dockerfile

Upgraded `setuptools` and `libc-bin` version used in container

Bump dependencies in container

---

batch/indexer_Token_Detail.py

Commit token cache to DB once per token in `Indexer_Token_Detail` batch

---

README.md
README_JA.md
app/__init__.py
app/main.py
batch/indexer_CompanyList.py
docs/ibet_wallet_api.yaml
pyproject.toml

Close: #1463 
- Removed the SQL query `DELETE FROM company;` to avoid full deletion.
- Added upsert query and record deletion query.

Avoid full deletion in Indexer_CompanyList batch process

---

Dockerfile
tests/Dockerfile

Upgrade Ubuntu

---

.pre-commit-config.yaml
Dockerfile
poetry.lock
pyproject.toml
tests/Dockerfile

Bump dependencies

---

Dockerfile
batch/indexer_Block_Tx_Data.py
batch/indexer_CompanyList.py
batch/indexer_Consume_Coupon.py
batch/indexer_DEX.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Token_Detail.py
batch/indexer_Token_Detail_ShortTerm.py
batch/indexer_Token_Holders.py
batch/indexer_Token_List.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/lib/misc.py
batch/log.py
batch/processor_Block_Sync_Status.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Token.py
batch/processor_Send_Chat_Webhook.py
batch/processor_Send_Mail.py
cmd/explorer/src/connector/__init__.py
migrations/manage.py
tests/Dockerfile
tests/batch/indexer_Token_Holders_test.py
tests/conftest.py

- Removed `sys.path.append` lines.

Remove `sys.path.append`

---

Dockerfile
tests/Dockerfile

Fix: #1474 
- Fixed invalid `PYTHONPATH` added in #1474.

Fix `PYTHONPATH`

---

batch/indexer_CompanyList.py
tests/batch/indexer_CompanyList_test.py

- Close: #1477
- Regarding the CompanyList synchronization process, I added a control to skip the process if there is no list difference from the previous cycle.
- Also, since the list is not updated in most cycles, we reverted to the old implementation of updating data with delete-insert.

Detect differences in CompanyList and update data

---

app/model/schema/base/__init__.py
app/model/schema/base/base.py
app/model/schema/messaging.py
app/model/schema/token_bond.py
app/model/schema/token_lock.py
docs/ibet_wallet_api.yaml
tests/app/messaging_SendEmail_test.py
tests/batch/processor_Notifications_Token_test.py

Improve email address max length validation

---

Dockerfile
tests/Dockerfile

- Add a line to Dockerfile in order to upgrade ubuntu packages in Docker container

Upgrade ubuntu package in Docker container

---

hardhat.config.js
package-lock.json
package.json
tests/app/eth_GetTransactionCount_test.py

- Update the version of hardhat.
- Change hardfork setting back to "berlin".

Bump hardhat

---

ENV_LIST.md
app/config.py
batch/processor_Send_Mail.py
tests/batch/processor_Send_Mail_test.py

Add email sending disallowance check

---

poetry.lock
pyproject.toml

Add a memory profiler for performance analysis.
https://bloomberg.github.io/memray/

Add memray

---

app/api/routers/eth.py
app/config.py
tests/app/eth_SendRawTransaction_test.py

Related to: #1518 
Changed the txpool waiting algorithm
- I changed the algorithm so that it sends without sleeping up to the threshold, and then starts sleeping abruptly once the threshold is exceeded.

Tuning txpool wait

---

app/api/routers/token_bond.py
app/api/routers/token_coupon.py
app/api/routers/token_membership.py
app/api/routers/token_share.py
tests/app/token_bond_StraightBondTokenDetails_test.py
tests/app/token_coupon_CouponTokenDetails_test.py
tests/app/token_membership_MembershipTokenDetails_test.py
tests/app/token_share_ShareTokenDetails_test.py

Return 404 Response when token details API receive the address of other token type in GET query

---

app/log.py

- Suppressed error logs raised by web3 request manager.

Suppress error logs raised by web3 module

---

app/api/routers/eth.py

- Make it enable to send DvP contract transaction via POST: `/Eth/SendRawTransaction`

Make it enable to send DvP contract transaction

---

.dockerignore
.github/actions/setup-test-image/action.yml
.github/workflows/pr.yml
Dockerfile
README.md
README_JA.md
app/__init__.py
app/contracts/__init__.py
app/main.py
docker-compose.yml
docs/ibet_wallet_api.yaml
pyproject.toml
tests/Dockerfile_unittest

- Multi-stage builds and slimmed down image sizes
- Update version notation to v24.9 except ibet-SmartContract

Multi-stage builds and slimmed down image sizes

---

.github/workflows/pr.yml
Dockerfile
tests/Dockerfile_unittest

Fix: #1531 
- Fixed write permissions of application directory.
- Modified test Dockerfile in the same way as prod image.

Fix write permissions of application directory

---

app/api/routers/token.py
app/model/schema/__init__.py
app/model/schema/token.py
tests/app/token_TokenStatus_test.py

Add `name` field to response of token status API

---

.github/workflows/pr.yml
.gitignore
docker-compose.yml
poetry.lock
pyproject.toml
tests/qa.sh

Measure test coverage

---

docs/ibet_wallet_api.yaml

Related to #1545 
Update API doc

[skip ci] Update api doc

---

app/config.py
batch/processor_Block_Sync_Status.py

Change `EXPECTED_BLOCKS_PER_SEC` from a constant to an environment variable

---

batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py

Speed up balance updates in indexer_Position batch

---

batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
tests/batch/indexer_Position_Bond_test.py
tests/batch/indexer_Position_Coupon_test.py
tests/batch/indexer_Position_Membership_test.py
tests/batch/indexer_Position_Share_test.py

Speed up balance updates in indexer_Position batch (24.6)

---

app/config.py
app/model/mail/mail.py
tests/batch/processor_Send_Mail_test.py

feat: support mail policy setting

---

app/config.py
app/model/mail/mail.py
tests/batch/processor_Send_Mail_test.py

close #1559 
(cherry pick https://github.com/BoostryJP/ibet-Wallet-API/pull/1560 and change default)

feat: Add SMTP policy option for mail text to ensure compliance with SMTP standards

---

app/api/routers/company_info.py
app/model/schema/company_info.py
docs/ibet_wallet_api.yaml
tests/app/company_info_CompanyInfo_test.py

Return the personal info address set for the specified issuer's token

---

README.md
README_JA.md
docker-compose.yml
package-lock.json
package.json
tests/Dockerfile_hardhat

- Support PostgreSQL v16.
- Update the hardhat image.

Update postgres and hardhat images

---

app/api/routers/token.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py
batch/processor_Notifications_Token.py
docs/ibet_wallet_api.yaml
tests/app/token_TokenStatus_test.py

Improve TaskGroup error logging

---

logger.py

fix log format

---

pyproject.toml
uv.lock

- Fix #1579 
- Added py-spy to prod image

Add py-spy to prod image

---

app/config.py
app/database/__init__.py
pyproject.toml
tests/batch/indexer_Token_Detail_test.py
tests/batch/indexer_Token_Holders_test.py
tests/batch/indexer_Token_List_test.py
tests/batch/indexer_TransferApproval_test.py
tests/batch/indexer_Transfer_test.py
tests/batch/processor_Notifications_Coupon_Exchange_test.py
tests/batch/processor_Notifications_Membership_Exchange_test.py
tests/batch/processor_Notifications_Token_test.py
tests/batch/processor_Send_Chat_Webhook_test.py
tests/conftest.py
uv.lock

Switch to asyncpg for async DB engine

---

app/contracts/contract.py
app/model/db/base.py
batch/indexer_Position_Bond.py
batch/indexer_Position_Coupon.py
batch/indexer_Position_Membership.py
batch/indexer_Position_Share.py
batch/indexer_Transfer.py
batch/indexer_TransferApproval.py
batch/processor_Notifications_Coupon_Exchange.py
batch/processor_Notifications_Membership_Exchange.py

- Close #1576 
- (This might also close #1535)

Reuse contract instance from on memory cache

---

app/api/routers/admin.py
app/model/schema/__init__.py
app/model/schema/admin.py
app/model/schema/base/__init__.py
app/model/schema/base/base.py
app/model/schema/token_bond.py
app/model/schema/token_coupon.py
app/model/schema/token_membership.py
app/model/schema/token_share.py
docs/ibet_wallet_api.yaml
tests/app/admin_Tokens_POST_test.py

Refactoring of Token Attribute Schema
None
- Modified the schema to manage token attribute-related schemas as a base schema.  
- Updated the Admin API interface to return token attributes when adding a new token.

Refactor token attributes schema

---

batch/indexer_CompanyList.py
batch/processor_Send_Chat_Webhook.py

Use system proxy settings for external resource connections with aiohttp. This change enables the application to respect proxy settings defined in environment variables (HTTP_PROXY, HTTPS_PROXY, etc.) when accessing external resources.
- Part of #1611 
- Implemented proxy support in aiohttp client configuration
- Added capability to respect system proxy settings (HTTP_PROXY, HTTPS_PROXY)

Use system proxy settings for external resource connections with aiohttp (25.3)

---

batch/indexer_Company_List.py
batch/indexer_PublicInfo_PublicAccountList.py
batch/indexer_PublicInfo_TokenList.py
batch/processor_Send_Chat_Webhook.py

Use system proxy settings for external resource connections with aiohttp. This change enables the application to respect proxy settings defined in environment variables (HTTP_PROXY, HTTPS_PROXY, etc.) when accessing external resources.
- Cherry pick from #1612 
- Close #1611 
- Implemented proxy support in aiohttp client configuration
- Added capability to respect system proxy settings (HTTP_PROXY, HTTPS_PROXY)

Use system proxy settings for external resource connections with aiohttp (25.6)

---

app/api/routers/token.py
app/model/db/idx_transfer.py
app/model/schema/__init__.py
app/model/schema/token.py
docs/ibet_wallet_api.yaml
tests/app/token_transfer_history_ListAllTransferHistory_test.py
tests/app/token_transfer_history_ListTokenTransferApprovalHistory_test.py
tests/app/token_transfer_history_ListTokenTransferHistory_test.py
tests/app/token_transfer_history_SearchTokenTransferApprovalHistory_test.py
tests/app/token_transfer_history_SearchTokenTransferHistory_test.py

Add a cross-account transfer history search API.
- Close #1614
- Add a `ListAllTransferHistory` API
- Rename other related APIs

Add ListAllTransferHistory query and refactor related tests

---

app/model/db/public_info.py
app/model/schema/public_info.py
docs/ibet_wallet_api.yaml
tests/app/public_info_ListAllPublicAccounts_test.py
tests/batch/indexer_PublicInfo_PublicAccountList_test.py

Added modified field to Public Account List API response
- Related to #1600 
- Added modified field to Public Account List API response

Add modified field to Public Account List response

---

batch/processor_Block_Sync_Status.py

Improve error logging for node connection failures in processor_Block_Sync_Status.py
- Close #1617 
- Change logging method of error logging from `.error()` to `.exception()` in processor_Blcok_Sync_Status.py

Improve error logging for node connection failures in processor_Block_Sync_Status.py

---

.github/dependabot.yml
.gitignore

Update .gitignore and add dependabot configuration for auto dependency management.
- Close #1625 
- Update .gitignore.
- Add dependabot configuration.

Add dependabot configuration for dependency management

---

app/utils/docs_utils.py

This pull request refactors and improves type annotations, error handling, and schema generation in `app/utils/docs_utils.py`. The changes enhance code clarity, enforce stricter type safety, and improve the generation of OpenAPI documentation.
- None
* Refactored type hints for `docs_utils.py`

Refactor type hints for docs_utils
